### ISSUE TITLE
ValueError using ovshell 0.6.1

### ISSUE THREAD

**Issue by condoratberlin** [kedder/openvario-shell#20]
I updated the openvario shell by using:
`opkg install ovmenu-ng ovmenu-ng-autostart --force-removal-of-dependent-packages`
Starting works fine, but after returning from any submenue to the main menu an ValueError rises:
```
Traceback (most recent call last):
  File "/usr/bin/ovshell", line 11, in <module>
    load_entry_point('openvario-shell==0.6.1', 'console_scripts', 'ovshell')()
  File "/usr/lib/python3.7/site-packages/ovshell/main.py", line 128, in main
    run(sys.argv[1:])
  File "/usr/lib/python3.7/site-packages/ovshell/main.py", line 119, in run
    urwidloop.run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 1494, in run
    reraise(*exc_info)
  File "/usr/lib/python3.7/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.7/site-packages/urwid/raw_display.py", line 501, in _parse_incomplete_input
    event_loop, callback, codes, wait_for_more=False)
  File "/usr/lib/python3.7/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.7/site-packages/urwid/wimp.py", line 651, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3.7/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3.7/site-packages/ovshell/widget.py", line 75, in keypress
    self._emit(self.signal_map[key])
  File "/usr/lib/python3.7/site-packages/urwid/widget.py", line 461, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3.7/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.7/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/lib/python3.7/site-packages/ovshell/screen.py", line 215, in _cancel_activity
    self.pop_activity()
  File "/usr/lib/python3.7/site-packages/ovshell/screen.py", line 185, in pop_activity
    self._reset_palette(prevactctx.palette)
  File "/usr/lib/python3.7/site-packages/ovshell/screen.py", line 232, in _reset_palette
    (basic, mono, high_88, high_256, high_true) = entry
ValueError: not enough values to unpack (expected 5, got 4)
```
I try to elaborate further details.

# System settings:
Openvario image:   20117(ov-thud)
XCSoar:                  git-r11
Sensor daemon:     git-r8
Vario daemon:        git-r11
Linux kernel:           Linux 5.2.0-rc2

**Comment by condoratberlin** [comment]
The `entry` raising the ValueError is the following:
`AttrSpec('default', 'default'), AttrSpec('default', 'default'), AttrSpec('default', 'default', colors=88), AttrSpec('default', 'default')`

**Comment by kedder** [comment]
Hm, this looks like an python3-urwid version mismatch. Do you remember what ovshell version you had before? I'd expect `2.1.1-r0` to be installed with ovshell-0.6.1

Can you show the output of this command:

```
opkg list-installed | grep urwid
```

Also, try updating everything:

```
opkg update
opkg list-upgradable
opkg upgrade
```

**Comment by condoratberlin** [comment]
You are right, `python3-urwid - 2.1.0-r0` is installed and an upgrade with 
```
opkg list-upgradable
opkg upgrade
```
resolved the issue, by upgrading to `python3-urwid - 2.1.1-r0`.
It can be closed.

**Comment by kedder** [comment]
Awesome! Btw, ovshell-6.1 includes it's own system upgrade utility, so you don't have to do that from command-line!
